{
  viewer {
    login
  }
  # If querying large volumes of data or many pages, it is probably useful
  # to check the rate limit stats on the response.
  #
  # You can also do a dry run. If you set dryRun to true:
  #   Calculate the cost for the query (stats are shown as if executed).
  #   The query is not evaluated (no data is returned and there is no cost).
  #   The 'rateLimit' field is the only key returned in 'data'.
  # See https://developer.github.com/v4/query/
  rateLimit(dryRun: true) {
    limit
    cost
    remaining
    resetAt
    nodeCount
  }
}
