# Get details of latest 100 commits only for all repos owned by an account, using paging across repos.
#
# Pages through repos but do not page through pages of commits, as nested cursors for
# the repo and commit level does not seem possible. So this cannot go beyond the
# most page of commits.
query ReposAndRecentCommitsPaged($owner: String!, $since: GitTimestamp, $isFork: Boolean, $cursor: String) {
	repositoryOwner(login: $owner) {
		repositories(first: 3, after: $cursor, isFork: $isFork) {
			totalCount
			pageInfo {
				hasNextPage
				endCursor
			}
			nodes {
				name
				defaultBranch: defaultBranchRef {
					name
					commits: target {
						... on Commit {
							history(first: 100, since: $since) {
								nodes {
									abbreviatedOid
								    authoredDate
									author {
										user {
											login
										}
									}
									committedDate
									committer {
										user {
											login
										}
									}
									changedFiles
									additions
									deletions
									message
								}
							}
						}
					}
				}
			}
		}
	}
}
