# Get starred repos of the current user.
#
# Parameters:
#	cursor: Optional cursor to allow for getting the next page of results. 
#		"Returns the elements in the list that come after the specified cursor."
#
# Sorting is also possible:
#	https://docs.github.com/en/graphql/reference/enums#starorderfield
# 	orderBy: { field: STARRED_AT, direction: ASC/DESC}
#
#	It doesn't look like sorting by repo name, push date etc. is possible here.
#
query StarredRepos($cursor: String) {
	viewer {
		starredRepositories(first: 100, after: $cursor) {
			totalCount
			pageInfo {
				hasNextPage
				endCursor
			}
			nodes {
				owner {
					login
				}
				name
				description: shortDescriptionHTML
				homepageUrl
				createdAt
				updatedAt
				latestRelease: releases(first: 1) {
					nodes {
						tagName
						createdAt
					}
				}
				branch: defaultBranchRef {
					name
				}
				url
				sshUrl
				forkCount
			}
		}
	}
}
