query AboutRepos($login: String!, $after: String) {
  repositoryOwner(login: $login) {
    repositories(isFork: false, first: 100, after: $after, orderBy: {field: NAME, direction: ASC}) {
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        name
        createdAt
        updatedAt
        description
        primaryLanguage {
          name
        }
        languages(first: 100) {
          nodes {
            name
          }
        }
      }
    }
  }
}
