# Get details of latest 100 commits for all repos owned by an account, using repo paging.
query ReposAndCommitsPaged($owner: String!, $since: GitTimestamp, $cursor: String) {
	repositoryOwner(login: $owner) {
		repositories(first: 100, after: $cursor, orderBy: { field: UPDATED_AT, direction: DESC }) {
			totalCount
			pageInfo {
				hasNextPage
				endCursor
			}
			nodes {
				name
				defaultBranch: defaultBranchRef {
					name
					commits: target {
						... on Commit {
							history(first: 100, since: $since) {
								nodes {
									abbreviatedOid
								    authoredDate
									author {
										user {
											login
										}
									}
									committedDate
									committer {
										user {
											login
										}
									}
									changedFiles
									additions
									deletions
									message
								}
							}
						}
					}
				}
			}
		}
	}
}
