# Get summary data about repos owned by an account, using paging.
query ReposAbout($owner: String!, $cursor: String) {
    repositoryOwner(login: $owner) {
        repositories(first: 100, after: $cursor, orderBy: { field: UPDATED_AT, direction: DESC }) {
            totalCount
            pageInfo {
                hasNextPage
                endCursor
            }
            nodes {
                name
                createdAt
                updatedAt
                description
                primaryLanguage {
                    name
                }
                languages(first: 100) {
                    nodes {
                        name
                    }
                }
            }
        }
    }
}
