{
  repository(owner: "michaelcurrin", name: "aggre-git") {
    name
    owner {
      login
    }
    defaultBranchRef {
      name
      target {
        ... on Commit {
          history(first: 3, after: "5c8a8566c0bc6b2d42991cf3e1034773e37aabe2 2") {
            totalCount
            edges {
              node {
                message
              }
              cursor
            }
            pageInfo {
              endCursor
              hasNextPage
            }
          }
        }
      }
    }
  }
}
